name: CI

on:
#   schedule:
#      - cron: '0,30 * * * *'  
  push:

jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
      
      
    - name: Install Dependence
      run: pip3 install easytrader
           pip3 install PyExecJS

    - name: Run trade.py
      run: python3 trade.py

        
    - name: Failure test
      if: failure()
      run: | 
        ls
        echo 55555  
